Broadcasting


In [3]:
import numpy as np
a=np.array([0,1,2])

a.shape

(3,)

In [ ]:
import numpy as np
a=np.tile(np.arange(0,40,10),(3,1))
print(a)

print("******************")
a=a.T
print(a)

[[ 0 10 20 30]
 [ 0 10 20 30]
 [ 0 10 20 30]]
******************
[[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]]


In [5]:
import numpy as np
a=np.tile(np.arange(0,40,10),(3,2))
print(a)

print("******************")
a=a.T
print(a)

[[ 0 10 20 30  0 10 20 30]
 [ 0 10 20 30  0 10 20 30]
 [ 0 10 20 30  0 10 20 30]]
******************
[[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]
 [ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]]


In [8]:
b=np.array([0,1,2])
b

array([0, 1, 2])

In [9]:
a + b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32],
       [ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [10]:
a=np.arange(0,40,10)
a.shape

(4,)

In [11]:
a=a[:,np.newaxis]
a.shape

(4, 1)

In [12]:
a

array([[ 0],
       [10],
       [20],
       [30]])

In [13]:
a+b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [ ]:
# 2D array of convert 1D Array:

a=np.array([[1,2,3],[4,5,6]])
a.ravel()

array([1, 2, 3, 4, 5, 6])

In [ ]:
a.T #Transpose

array([[1, 4],
       [2, 5],
       [3, 6]])

In [16]:
a.T.ravel()

array([1, 4, 2, 5, 3, 6])

In [17]:
print(a.shape)
print(a)

(2, 3)
[[1 2 3]
 [4 5 6]]


In [18]:
b=a.ravel()
print(b)

[1 2 3 4 5 6]


In [19]:
b=b.reshape((2,3))
b

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
b[0,0]=100
a

array([[100,   2,   3],
       [  4,   5,   6]])