# Numpy

In [5]:
import numpy as np
a=np.array([0,1,2,3])
print(a)

print(np.arange(10))

[0 1 2 3]
[0 1 2 3 4 5 6 7 8 9]


In [57]:
L = range(1000)
%timeit [i**2 for i in L]

53.4 μs ± 1.08 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [58]:
a=np.arange(1000)
%timeit a**2

1.44 μs ± 11.2 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


The Numpy array object Numpy Arrays

In [59]:
# Print dimension
a.ndim

1

In [60]:
#Shape
a.shape

(1000,)

In [61]:
# length
len(a)

1000

In [62]:
# 2-D, 3-D....
b=np.array([[0,1,2],[3,4,5]])
b

array([[0, 1, 2],
       [3, 4, 5]])

In [63]:
b.ndim

2

In [64]:
b.shape

(2, 3)

In [65]:
len(b)

2

In [66]:
c=np.array([[[0,1],[2,3]],[[4,5],[6,7]]])
c



array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [67]:
c=np.arange(10)
print(c) 



[0 1 2 3 4 5 6 7 8 9]


In [68]:
a=np.linspace(0,10,6) #start,end,number of points
print(a)
a

[ 0.  2.  4.  6.  8. 10.]


array([ 0.,  2.,  4.,  6.,  8., 10.])

In [69]:
#common arrays
a=np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [70]:
a=np.zeros((3,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [71]:
c=np.eye(3)
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [72]:
c=np.eye(3,2)
c

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [73]:
a=np.diag([1,2,3,4])#construct a diagonal array.
a 

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [74]:
np.diag(a)

array([1, 2, 3, 4])

In [75]:
a=np.random.rand(4) #random array
a

array([0.42575841, 0.00399663, 0.66564966, 0.5646237 ])

In [76]:
a=np.random.randn(4) #random array this function are positive and negative answer
a

array([ 1.62950547, -1.44095104,  1.71210426, -0.13150426])

In [77]:
a=np.arange(10)
a.dtype

dtype('int64')

In [78]:
a=np.arange(10,dtype='float64')
a 

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [79]:
a=np.zeros((3,3))
print(a)
a.dtype

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


dtype('float64')

In [80]:
d=np.array([1+2j, 2+4j]) #complex datatype

print(d.dtype)

complex128


In [81]:
b=np.array([True,False,True,False])
print(b.dtype)

bool


In [82]:
# for multidimentional arrays,
a=np.diag([1,2,3])
print(a[2,2])

3


In [83]:
a=[2,2]=5 #change the value
a

SyntaxError: cannot assign to literal (3438054981.py, line 1)

In [ ]:
a=np.arange(10)
a




array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a[1:8:2] #start index and last index and space

array([1, 3, 5, 7])

In [ ]:
a=np.arange(10)
a[5:]=10
a

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

In [ ]:
b=np.arange(5)
a[5:]=b[::-1]
a 

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

In [ ]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
b=a[::2]
b 

array([0, 2, 4, 6, 8])

In [90]:
np.shares_memory(a,b)

False

In [92]:
b[0]=10
b

array([ True, False,  True, False])

In [86]:
np.shares_memory(a,b)

False

In [88]:
a


array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [93]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [94]:
a=np.arange(10)
c=a[::2].copy()
c

array([0, 2, 4, 6, 8])

In [95]:
np.shares_memory(a,c)

False

In [96]:
c[0]=10
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
a= np.random.randint(0,20,15)
a

array([ 6, 18,  4, 11, 17, 10, 14,  7, 18,  5,  6,  4,  4, 14, 10],
      dtype=int32)

In [9]:
mask=(a%2==0)


In [10]:
extract_from_a=a[mask]
extract_from_a

array([ 6, 18,  4, 10, 14, 18,  6,  4,  4, 14, 10], dtype=int32)

In [11]:
a[mask]=-1
a

array([-1, -1, -1, 11, 17, -1, -1,  7, -1,  5, -1, -1, -1, -1, -1],
      dtype=int32)

In [12]:
a=np.arange(0,100,10)
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [13]:
a[[2,3,2,4,2]]

array([20, 30, 20, 40, 20])

In [14]:
a[[9,7]]=-200
a

array([   0,   10,   20,   30,   40,   50,   60, -200,   80, -200])

Elementwise operations

In [15]:
a=np.array([1,2,3,4])
a+1

array([2, 3, 4, 5])

In [16]:
a ** 2

array([ 1,  4,  9, 16])

In [17]:
b=np.ones(4)+1
a-b

array([-1.,  0.,  1.,  2.])

In [19]:
c=np.diag([1,2,3,4])

print(c * c)
print("****************")
print(c.dot(c))

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]
****************
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


In [20]:
a=np.array([1,2,3,4])
b=np.array([1,2,3,4])

a == b

array([ True,  True,  True,  True])

In [21]:
a>b

array([False, False, False, False])

In [28]:
a=np.array([1,2,3,4])
b=np.array([5,2,2,4])
c=np.array([1,2,3,4])

print(np.array_equal(a,b))

print(np.array_equal(a,c))


False
True


In [29]:
a=np.array([1,1,0,0], dtype=bool)
b=np.array([1,0,1,0], dtype=bool)

np.logical_or(a,b)

array([ True,  True,  True, False])

In [30]:
np.logical_and(a,b)

array([ True, False, False, False])

In [31]:
a=np.arange(5)

In [34]:
x=np.array([1,2,3,4])
np.sum(x)


np.int64(10)

In [35]:
x.sum(axis=0)

np.int64(10)

In [39]:
a=np.array([1,2,3,4])
b=np.array([5,2,2,4])
c=np.array([1,2,3,4])

((a<=b)&(b<=c)).all()

np.False_

In [40]:
x=np.array([1,2,3,1])
y=np.array([[1,2,3],[5,6,1]])
x.mean()

np.float64(1.75)

In [41]:
np.median(x)

np.float64(1.5)

In [42]:
np.median(y,axis=-1)

array([2., 5.])

In [ ]:
x.std()

np.float64(0.82915619758885)